### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by mehdi61** [dcaribou/transfermarkt-datasets#66]
--> Acquiring games
Traceback (most recent call last):
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\api\client.py", line 214, in _retrieve_server_version
return self.version(api_version=False)["ApiVersion"]
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\api\daemon.py", line 181, in version
return self._result(self._get(url), json=True)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\utils\decorators.py", line 46, in inner
return f(self, *args, **kwargs)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\api\client.py", line 237, in _get
return self.get(url, **self._set_request_timeout(kwargs))
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
resp = conn.urlopen(
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1279, in request
self._send_request(method, url, body, headers, encode_chunked)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1325, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1274, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1034, in _send_output
self.send(msg)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 974, in send
self.connect()
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\transport\npipeconn.py", line 29, in connect
sock.connect(self.npipe_path)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\transport\npipesocket.py", line 22, in wrapped
return f(self, *args, **kwargs)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\transport\npipesocket.py", line 71, in connect
raise e
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\transport\npipesocket.py", line 51, in connect
handle = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Mehdi\Downloads\transfermarkt-datasets-master\transfermarkt-datasets-master\1_acquire.py", line 155, in <module>
acquired_data = acquire_asset(
File "C:\Users\Mehdi\Downloads\transfermarkt-datasets-master\transfermarkt-datasets-master\1_acquire.py", line 106, in acquire_asset
docker_client = docker.from_env()
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\client.py", line 96, in from_env
return cls(
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\client.py", line 45, in init
self.api = APIClient(*args, **kwargs)
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\api\client.py", line 197, in init
self._version = self._retrieve_server_version()
File "C:\Users\Mehdi\AppData\Local\Programs\Python\Python39\lib\site-packages\docker\api\client.py", line 221, in _retrieve_server_version
raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

**Comment by dcaribou** [comment]
Hey @mehdi61, could you share more details about what you did to get the issue? For example
* I can already see that you are on Windows
* Did you use the provided [`environment.yml`](https://github.com/dcaribou/transfermarkt-datasets/blob/master/environment.yml) file to setup your environment with the necessary python packages? If not, what did you use?
* How are you trying to run it? Are you invoking the `1_acquiring.py` script? `run_pipeline.sh`?
* Do you have a healthy local docker installation?
